/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/case/list': RouteRecordInfo<'/case/list', '/case/list', Record<never, never>, Record<never, never>>,
    '/case/new': RouteRecordInfo<'/case/new', '/case/new', Record<never, never>, Record<never, never>>,
    '/customers/edit': RouteRecordInfo<'/customers/edit', '/customers/edit', Record<never, never>, Record<never, never>>,
    '/customers/list': RouteRecordInfo<'/customers/list', '/customers/list', Record<never, never>, Record<never, never>>,
    '/customers/new': RouteRecordInfo<'/customers/new', '/customers/new', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/oil/list': RouteRecordInfo<'/oil/list', '/oil/list', Record<never, never>, Record<never, never>>,
  }
}
